/*
 * Generated by Bluespec Compiler (build f2da894e)
 * 
 * On Mon Nov  8 19:34:51 IST 2021
 * 
 */
extern "C" {
  void initialize();
  unsigned int readConfig(unsigned int );
  unsigned int readInput(unsigned int );
}
