/*
 * Generated by Bluespec Compiler (build f2da894e)
 * 
 * On Sat Jul 17 19:53:59 IST 2021
 * 
 */

/* Generation options: */
#ifndef __mkBinary_h__
#define __mkBinary_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkBinary module */
class MOD_mkBinary : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt32> INST_cOut;
  MOD_Reg<tUInt8> INST_op;
 
 /* Constructor */
 public:
  MOD_mkBinary(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
 
 /* Local definitions */
 private:
  tUInt8 DEF_b__h134;
 
 /* Rules */
 public:
 
 /* Methods */
 public:
  void METH_a_b(tUInt32 ARG_a_b__a, tUInt32 ARG_a_b__b);
  tUInt8 METH_RDY_a_b();
  tUInt32 METH_c();
  tUInt8 METH_RDY_c();
  void METH_set_operation(tUInt8 ARG_set_operation__ox);
  tUInt8 METH_RDY_set_operation();
  tUInt8 METH_get_operation();
  tUInt8 METH_RDY_get_operation();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkBinary &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkBinary &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkBinary &backing);
};

#endif /* ifndef __mkBinary_h__ */
