/*
 * Generated by Bluespec Compiler (build 00185f79)
 * 
 * On Sun May 23 21:16:52 IST 2021
 * 
 */
#include "bluesim_primitives.h"
#include "mkLine3.h"


/* Literal declarations */
static unsigned int const UWide_literal_800_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa_arr[] = { 2863311530u,
																																2863311530u,
																																2863311530u,
																																2863311530u,
																																2863311530u,
																																2863311530u,
																																2863311530u,
																																2863311530u,
																																2863311530u,
																																2863311530u,
																																2863311530u,
																																2863311530u,
																																2863311530u,
																																2863311530u,
																																2863311530u,
																																2863311530u,
																																2863311530u,
																																2863311530u,
																																2863311530u,
																																2863311530u,
																																2863311530u,
																																2863311530u,
																																2863311530u,
																																2863311530u,
																																2863311530u };
static tUWide const UWide_literal_800_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa(800u,
																														UWide_literal_800_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa_arr);


/* Constructor */
MOD_mkLine3::MOD_mkLine3(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST__unnamed_(simHdl, "_unnamed_", this),
    INST__unnamed__1(simHdl, "_unnamed__1", this),
    INST__unnamed__2(simHdl, "_unnamed__2", this),
    INST__unnamed__3(simHdl, "_unnamed__3", this),
    INST__unnamed__4(simHdl, "_unnamed__4", this),
    INST__unnamed__5(simHdl, "_unnamed__5", this),
    INST__unnamed__6(simHdl, "_unnamed__6", this),
    INST__unnamed__7(simHdl, "_unnamed__7", this),
    INST_alpha(simHdl, "alpha", this, 9u, 8u, (tUInt8)0u),
    INST_c1(simHdl, "c1", this, 9u, 0u, (tUInt8)0u),
    INST_c2(simHdl, "c2", this, 9u, 0u, (tUInt8)0u),
    INST_collectWindow(simHdl, "collectWindow", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_img(simHdl, "img", this, 9u, 21u, (tUInt8)0u),
    INST_instream(simHdl, "instream", this, 16u, 2u, (tUInt8)1u, 0u),
    INST_outQ(simHdl, "outQ", this, 1024u, 2u, (tUInt8)1u, 0u),
    INST_r1(simHdl, "r1", this, 9u, 0u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u),
    DEF__unnamed__2_enQdeQ___d84(128u),
    DEF__unnamed__1_enQdeQ___d86(128u),
    DEF__unnamed__enQdeQ___d88(128u),
    DEF_outQ_first____d91(1024u),
    DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4_5_CONCAT_u_ETC___d90(1024u),
    DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85(928u)
{
  PORT_get.setSize(512u);
  PORT_get.clear();
  symbol_count = 19u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkLine3::init_symbols_0()
{
  init_symbol(&symbols[0u], "_unnamed_", SYM_MODULE, &INST__unnamed_);
  init_symbol(&symbols[1u], "_unnamed__1", SYM_MODULE, &INST__unnamed__1);
  init_symbol(&symbols[2u], "_unnamed__2", SYM_MODULE, &INST__unnamed__2);
  init_symbol(&symbols[3u], "_unnamed__3", SYM_MODULE, &INST__unnamed__3);
  init_symbol(&symbols[4u], "_unnamed__4", SYM_MODULE, &INST__unnamed__4);
  init_symbol(&symbols[5u], "_unnamed__5", SYM_MODULE, &INST__unnamed__5);
  init_symbol(&symbols[6u], "_unnamed__6", SYM_MODULE, &INST__unnamed__6);
  init_symbol(&symbols[7u], "_unnamed__7", SYM_MODULE, &INST__unnamed__7);
  init_symbol(&symbols[8u], "alpha", SYM_MODULE, &INST_alpha);
  init_symbol(&symbols[9u], "c1", SYM_MODULE, &INST_c1);
  init_symbol(&symbols[10u], "c2", SYM_MODULE, &INST_c2);
  init_symbol(&symbols[11u], "collectWindow", SYM_MODULE, &INST_collectWindow);
  init_symbol(&symbols[12u], "get", SYM_PORT, &PORT_get, 512u);
  init_symbol(&symbols[13u], "img", SYM_MODULE, &INST_img);
  init_symbol(&symbols[14u], "instream", SYM_MODULE, &INST_instream);
  init_symbol(&symbols[15u], "outQ", SYM_MODULE, &INST_outQ);
  init_symbol(&symbols[16u], "RL__putDataInLB0", SYM_RULE);
  init_symbol(&symbols[17u], "RL__serialShiftLeft", SYM_RULE);
  init_symbol(&symbols[18u], "r1", SYM_MODULE, &INST_r1);
}


/* Rule actions */

void MOD_mkLine3::RL__putDataInLB0()
{
  tUInt32 DEF_r1_7_PLUS_1___d30;
  tUInt8 DEF_r1_7_ULT_7___d28;
  tUInt8 DEF_c1_1_EQ_img_2_MINUS_1_3_4_AND_r1_7_ULT_7_8___d29;
  tUInt8 DEF_c1_1_EQ_img_2_MINUS_1_3_4_AND_NOT_r1_7_ULT_7_8_1___d32;
  DEF_x__h5702 = INST_r1.METH_read();
  DEF_instream_first____d34 = INST_instream.METH_first();
  DEF_b__h1288 = INST_c1.METH_read();
  DEF_b__h1307 = INST_img.METH_read();
  DEF_r1_7_EQ_6___d40 = DEF_x__h5702 == 6u;
  DEF_r1_7_EQ_5___d39 = DEF_x__h5702 == 5u;
  DEF_r1_7_EQ_4___d38 = DEF_x__h5702 == 4u;
  DEF_r1_7_EQ_3___d37 = DEF_x__h5702 == 3u;
  DEF_r1_7_EQ_2___d36 = DEF_x__h5702 == 2u;
  DEF_r1_7_EQ_0___d33 = DEF_x__h5702 == 0u;
  DEF_r1_7_EQ_1___d35 = DEF_x__h5702 == 1u;
  DEF_r1_7_EQ_7___d41 = DEF_x__h5702 == 7u;
  DEF_c1_1_EQ_img_2_MINUS_1_3___d24 = DEF_b__h1288 == (511u & (DEF_b__h1307 - 1u));
  DEF_IF_c1_1_EQ_img_2_MINUS_1_3_4_THEN_0_ELSE_c1_1__ETC___d26 = DEF_c1_1_EQ_img_2_MINUS_1_3___d24 ? 0u : 511u & (DEF_b__h1288 + 1u);
  DEF_r1_7_ULT_7___d28 = DEF_x__h5702 < 7u;
  DEF_c1_1_EQ_img_2_MINUS_1_3_4_AND_NOT_r1_7_ULT_7_8_1___d32 = DEF_c1_1_EQ_img_2_MINUS_1_3___d24 && !DEF_r1_7_ULT_7___d28;
  DEF_c1_1_EQ_img_2_MINUS_1_3_4_AND_r1_7_ULT_7_8___d29 = DEF_c1_1_EQ_img_2_MINUS_1_3___d24 && DEF_r1_7_ULT_7___d28;
  DEF_r1_7_PLUS_1___d30 = 511u & (DEF_x__h5702 + 1u);
  INST_c1.METH_write(DEF_IF_c1_1_EQ_img_2_MINUS_1_3_4_THEN_0_ELSE_c1_1__ETC___d26);
  if (DEF_c1_1_EQ_img_2_MINUS_1_3_4_AND_r1_7_ULT_7_8___d29)
    INST_r1.METH_write(DEF_r1_7_PLUS_1___d30);
  if (DEF_c1_1_EQ_img_2_MINUS_1_3_4_AND_NOT_r1_7_ULT_7_8_1___d32)
    INST_collectWindow.METH_write((tUInt8)1u);
  INST_instream.METH_deq();
  if (DEF_r1_7_EQ_0___d33)
    INST__unnamed_.METH_enq(DEF_instream_first____d34);
  if (DEF_r1_7_EQ_1___d35)
    INST__unnamed__1.METH_enq(DEF_instream_first____d34);
  if (DEF_r1_7_EQ_2___d36)
    INST__unnamed__2.METH_enq(DEF_instream_first____d34);
  if (DEF_r1_7_EQ_3___d37)
    INST__unnamed__3.METH_enq(DEF_instream_first____d34);
  if (DEF_r1_7_EQ_4___d38)
    INST__unnamed__4.METH_enq(DEF_instream_first____d34);
  if (DEF_r1_7_EQ_5___d39)
    INST__unnamed__5.METH_enq(DEF_instream_first____d34);
  if (DEF_r1_7_EQ_7___d41)
    INST__unnamed__7.METH_enq(DEF_instream_first____d34);
  if (DEF_r1_7_EQ_6___d40)
    INST__unnamed__6.METH_enq(DEF_instream_first____d34);
}

void MOD_mkLine3::RL__serialShiftLeft()
{
  tUInt8 DEF_c1_1_ULT_img_2_MINUS_alpha_0_MINUS_1_1_2___d83;
  tUInt32 DEF_IF_r1_7_EQ_7_1_THEN_instream_first__4_BITS_15__ETC___d79;
  tUInt32 DEF_IF_r1_7_EQ_1_5_THEN_instream_first__4_ELSE_unn_ETC___d64;
  tUInt32 DEF_IF_r1_7_EQ_0_3_THEN_instream_first__4_ELSE_unn_ETC___d62;
  tUInt32 DEF_IF_r1_7_EQ_2_6_THEN_instream_first__4_ELSE_unn_ETC___d66;
  tUInt32 DEF_IF_r1_7_EQ_3_7_THEN_instream_first__4_ELSE_unn_ETC___d68;
  tUInt32 DEF_IF_r1_7_EQ_4_8_THEN_instream_first__4_ELSE_unn_ETC___d70;
  tUInt32 DEF_IF_r1_7_EQ_5_9_THEN_instream_first__4_ELSE_unn_ETC___d72;
  tUInt32 DEF_IF_r1_7_EQ_6_0_THEN_instream_first__4_ELSE_unn_ETC___d74;
  tUInt8 DEF_x_first_f__h1626;
  tUInt32 DEF_x_first_i__h1625;
  tUInt32 DEF_b__h5947;
  tUWide DEF_AVMeth__unnamed__2_enQdeQ(128u, false);
  tUWide DEF_AVMeth__unnamed__1_enQdeQ(128u, false);
  tUWide DEF_AVMeth__unnamed__enQdeQ(128u, false);
  DEF_x__h5702 = INST_r1.METH_read();
  DEF_instream_first____d34 = INST_instream.METH_first();
  DEF_b__h1288 = INST_c1.METH_read();
  DEF_b__h1307 = INST_img.METH_read();
  DEF_b__h5947 = INST_alpha.METH_read();
  DEF_x_first_i__h1625 = (tUInt32)(DEF_instream_first____d34 >> 1u);
  DEF_x_first_f__h1626 = (tUInt8)((tUInt8)1u & DEF_instream_first____d34);
  DEF_r1_7_EQ_6___d40 = DEF_x__h5702 == 6u;
  DEF_IF_r1_7_EQ_6_0_THEN_instream_first__4_ELSE_unn_ETC___d74 = DEF_r1_7_EQ_6___d40 ? DEF_instream_first____d34 : INST__unnamed__7.METH_read();
  DEF_r1_7_EQ_5___d39 = DEF_x__h5702 == 5u;
  DEF_IF_r1_7_EQ_5_9_THEN_instream_first__4_ELSE_unn_ETC___d72 = DEF_r1_7_EQ_5___d39 ? DEF_instream_first____d34 : INST__unnamed__6.METH_read();
  DEF_r1_7_EQ_3___d37 = DEF_x__h5702 == 3u;
  DEF_r1_7_EQ_4___d38 = DEF_x__h5702 == 4u;
  DEF_IF_r1_7_EQ_4_8_THEN_instream_first__4_ELSE_unn_ETC___d70 = DEF_r1_7_EQ_4___d38 ? DEF_instream_first____d34 : INST__unnamed__5.METH_read();
  DEF_IF_r1_7_EQ_3_7_THEN_instream_first__4_ELSE_unn_ETC___d68 = DEF_r1_7_EQ_3___d37 ? DEF_instream_first____d34 : INST__unnamed__4.METH_read();
  DEF_r1_7_EQ_2___d36 = DEF_x__h5702 == 2u;
  DEF_IF_r1_7_EQ_2_6_THEN_instream_first__4_ELSE_unn_ETC___d66 = DEF_r1_7_EQ_2___d36 ? DEF_instream_first____d34 : INST__unnamed__3.METH_read();
  DEF_r1_7_EQ_0___d33 = DEF_x__h5702 == 0u;
  DEF_IF_r1_7_EQ_0_3_THEN_instream_first__4_ELSE_unn_ETC___d62 = DEF_r1_7_EQ_0___d33 ? DEF_instream_first____d34 : INST__unnamed__1.METH_read();
  DEF_r1_7_EQ_1___d35 = DEF_x__h5702 == 1u;
  DEF_IF_r1_7_EQ_1_5_THEN_instream_first__4_ELSE_unn_ETC___d64 = DEF_r1_7_EQ_1___d35 ? DEF_instream_first____d34 : INST__unnamed__2.METH_read();
  DEF_r1_7_EQ_7___d41 = DEF_x__h5702 == 7u;
  DEF_c1_1_EQ_img_2_MINUS_1_3___d24 = DEF_b__h1288 == (511u & (DEF_b__h1307 - 1u));
  DEF_IF_c1_1_EQ_img_2_MINUS_1_3_4_THEN_0_ELSE_c1_1__ETC___d26 = DEF_c1_1_EQ_img_2_MINUS_1_3___d24 ? 0u : 511u & (DEF_b__h1288 + 1u);
  DEF_IF_r1_7_EQ_7_1_THEN_instream_first__4_BITS_15__ETC___d79 = 65535u & (((DEF_r1_7_EQ_7___d41 ? DEF_x_first_i__h1625 : 0u) << 1u) | (tUInt32)(DEF_r1_7_EQ_7___d41 && DEF_x_first_f__h1626));
  DEF_c1_1_ULT_img_2_MINUS_alpha_0_MINUS_1_1_2___d83 = DEF_b__h1288 < (511u & (DEF_b__h1307 - (511u & (DEF_b__h5947 - 1u))));
  INST_instream.METH_deq();
  DEF_AVMeth__unnamed__enQdeQ = INST__unnamed_.METH_enQdeQ(DEF_IF_r1_7_EQ_0_3_THEN_instream_first__4_ELSE_unn_ETC___d62);
  DEF__unnamed__enQdeQ___d88 = DEF_AVMeth__unnamed__enQdeQ;
  DEF_AVMeth__unnamed__1_enQdeQ = INST__unnamed__1.METH_enQdeQ(DEF_IF_r1_7_EQ_1_5_THEN_instream_first__4_ELSE_unn_ETC___d64);
  DEF__unnamed__1_enQdeQ___d86 = DEF_AVMeth__unnamed__1_enQdeQ;
  DEF_AVMeth__unnamed__2_enQdeQ = INST__unnamed__2.METH_enQdeQ(DEF_IF_r1_7_EQ_2_6_THEN_instream_first__4_ELSE_unn_ETC___d66);
  DEF__unnamed__2_enQdeQ___d84 = DEF_AVMeth__unnamed__2_enQdeQ;
  DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85.set_whole_word(UWide_literal_800_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.get_whole_word(24u),
							       28u).set_whole_word(UWide_literal_800_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.get_whole_word(23u),
										   27u).set_whole_word(UWide_literal_800_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.get_whole_word(22u),
												       26u).set_whole_word(UWide_literal_800_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.get_whole_word(21u),
															   25u).set_whole_word(UWide_literal_800_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.get_whole_word(20u),
																	       24u).set_whole_word(UWide_literal_800_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.get_whole_word(19u),
																				   23u).set_whole_word(UWide_literal_800_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.get_whole_word(18u),
																						       22u).set_whole_word(UWide_literal_800_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.get_whole_word(17u),
																									   21u).set_whole_word(UWide_literal_800_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.get_whole_word(16u),
																											       20u).set_whole_word(UWide_literal_800_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.get_whole_word(15u),
																														   19u).set_whole_word(UWide_literal_800_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.get_whole_word(14u),
																																       18u).set_whole_word(UWide_literal_800_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.get_whole_word(13u),
																																			   17u).set_whole_word(UWide_literal_800_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.get_whole_word(12u),
																																					       16u).set_whole_word(UWide_literal_800_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.get_whole_word(11u),
																																								   15u).set_whole_word(UWide_literal_800_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.get_whole_word(10u),
																																										       14u).set_whole_word(UWide_literal_800_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.get_whole_word(9u),
																																													   13u).set_whole_word(UWide_literal_800_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.get_whole_word(8u),
																																															       12u).set_whole_word(UWide_literal_800_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.get_whole_word(7u),
																																																		   11u).set_whole_word(UWide_literal_800_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.get_whole_word(6u),
																																																				       10u).set_whole_word(UWide_literal_800_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.get_whole_word(5u),
																																																							   9u).set_whole_word(UWide_literal_800_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.get_whole_word(4u),
																																																									      8u).set_whole_word(UWide_literal_800_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.get_whole_word(3u),
																																																												 7u).set_whole_word(UWide_literal_800_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.get_whole_word(2u),
																																																														    6u).set_whole_word(UWide_literal_800_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.get_whole_word(1u),
																																																																       5u).build_concat((((tUInt64)(UWide_literal_800_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.get_whole_word(0u))) << 32u) | (tUInt64)(DEF__unnamed__2_enQdeQ___d84.get_whole_word(3u)),
																																																																			96u,
																																																																			64u).set_whole_word(DEF__unnamed__2_enQdeQ___d84.get_whole_word(2u),
																																																																					    2u).set_whole_word(DEF__unnamed__2_enQdeQ___d84.get_whole_word(1u),
																																																																							       1u).set_whole_word(DEF__unnamed__2_enQdeQ___d84.get_whole_word(0u),
																																																																										  0u);
  DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4_5_CONCAT_u_ETC___d90.set_whole_word(DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85.get_whole_word(28u),
									      31u).set_whole_word(DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85.get_whole_word(27u),
												  30u).set_whole_word(DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85.get_whole_word(26u),
														      29u).set_whole_word(DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85.get_whole_word(25u),
																	  28u).set_whole_word(DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85.get_whole_word(24u),
																			      27u).set_whole_word(DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85.get_whole_word(23u),
																						  26u).set_whole_word(DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85.get_whole_word(22u),
																								      25u).set_whole_word(DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85.get_whole_word(21u),
																											  24u).set_whole_word(DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85.get_whole_word(20u),
																													      23u).set_whole_word(DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85.get_whole_word(19u),
																																  22u).set_whole_word(DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85.get_whole_word(18u),
																																		      21u).set_whole_word(DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85.get_whole_word(17u),
																																					  20u).set_whole_word(DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85.get_whole_word(16u),
																																							      19u).set_whole_word(DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85.get_whole_word(15u),
																																										  18u).set_whole_word(DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85.get_whole_word(14u),
																																												      17u).set_whole_word(DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85.get_whole_word(13u),
																																															  16u).set_whole_word(DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85.get_whole_word(12u),
																																																	      15u).set_whole_word(DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85.get_whole_word(11u),
																																																				  14u).set_whole_word(DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85.get_whole_word(10u),
																																																						      13u).set_whole_word(DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85.get_whole_word(9u),
																																																									  12u).set_whole_word(DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85.get_whole_word(8u),
																																																											      11u).set_whole_word(DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85.get_whole_word(7u),
																																																														  10u).set_whole_word(DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85.get_whole_word(6u),
																																																																      9u).set_whole_word(DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85.get_whole_word(5u),
																																																																			 8u).set_whole_word(DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85.get_whole_word(4u),
																																																																					    7u).set_whole_word(DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85.get_whole_word(3u),
																																																																							       6u).set_whole_word(DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85.get_whole_word(2u),
																																																																										  5u).set_whole_word(DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85.get_whole_word(1u),
																																																																												     4u).build_concat((((tUInt64)(DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85.get_whole_word(0u))) << 32u) | (tUInt64)(primExtract32(32u,
																																																																																												       128u,
																																																																																												       DEF__unnamed__1_enQdeQ___d86,
																																																																																												       32u,
																																																																																												       47u,
																																																																																												       32u,
																																																																																												       16u)),
																																																																														      64u,
																																																																														      64u).set_whole_word((DEF__unnamed__1_enQdeQ___d86.get_bits_in_word32(0u,
																																																																																							   0u,
																																																																																							   16u) << 16u) | DEF__unnamed__enQdeQ___d88.get_bits_in_word32(1u,
																																																																																															0u,
																																																																																															16u),
																																																																																	  1u).set_whole_word(DEF__unnamed__enQdeQ___d88.get_whole_word(0u),
																																																																																			     0u);
  INST__unnamed__3.METH_enQdeQ(DEF_IF_r1_7_EQ_3_7_THEN_instream_first__4_ELSE_unn_ETC___d68);
  INST__unnamed__4.METH_enQdeQ(DEF_IF_r1_7_EQ_4_8_THEN_instream_first__4_ELSE_unn_ETC___d70);
  INST__unnamed__5.METH_enQdeQ(DEF_IF_r1_7_EQ_5_9_THEN_instream_first__4_ELSE_unn_ETC___d72);
  INST__unnamed__6.METH_enQdeQ(DEF_IF_r1_7_EQ_6_0_THEN_instream_first__4_ELSE_unn_ETC___d74);
  INST__unnamed__7.METH_enQdeQ(DEF_IF_r1_7_EQ_7_1_THEN_instream_first__4_BITS_15__ETC___d79);
  INST_c1.METH_write(DEF_IF_c1_1_EQ_img_2_MINUS_1_3_4_THEN_0_ELSE_c1_1__ETC___d26);
  if (DEF_c1_1_ULT_img_2_MINUS_alpha_0_MINUS_1_1_2___d83)
    INST_outQ.METH_enq(DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4_5_CONCAT_u_ETC___d90);
}


/* Methods */

void MOD_mkLine3::METH_putFmap(tUInt32 ARG_putFmap_datas)
{
  INST_instream.METH_enq(ARG_putFmap_datas);
}

tUInt8 MOD_mkLine3::METH_RDY_putFmap()
{
  tUInt8 DEF_CAN_FIRE_putFmap;
  tUInt8 PORT_RDY_putFmap;
  DEF_CAN_FIRE_putFmap = INST_instream.METH_i_notFull();
  PORT_RDY_putFmap = DEF_CAN_FIRE_putFmap;
  return PORT_RDY_putFmap;
}

tUWide MOD_mkLine3::METH_get()
{
  DEF_outQ_first____d91 = INST_outQ.METH_first();
  wop_primExtractWide(512u, 1024u, DEF_outQ_first____d91, 32u, 511u, 32u, 0u, PORT_get);
  INST_outQ.METH_deq();
  return PORT_get;
}

tUInt8 MOD_mkLine3::METH_RDY_get()
{
  tUInt8 DEF_CAN_FIRE_get;
  tUInt8 PORT_RDY_get;
  DEF_CAN_FIRE_get = INST_outQ.METH_i_notEmpty();
  PORT_RDY_get = DEF_CAN_FIRE_get;
  return PORT_RDY_get;
}

void MOD_mkLine3::METH_reset(tUInt32 ARG_reset_imageSize)
{
  INST_img.METH_write(ARG_reset_imageSize);
}

tUInt8 MOD_mkLine3::METH_RDY_reset()
{
  tUInt8 DEF_CAN_FIRE_reset;
  tUInt8 PORT_RDY_reset;
  DEF_CAN_FIRE_reset = (tUInt8)1u;
  PORT_RDY_reset = DEF_CAN_FIRE_reset;
  return PORT_RDY_reset;
}

void MOD_mkLine3::METH_clean()
{
  INST__unnamed_.METH_clean();
  INST__unnamed__1.METH_clean();
  INST__unnamed__2.METH_clean();
  INST__unnamed__3.METH_clean();
  INST__unnamed__4.METH_clean();
  INST__unnamed__6.METH_clean();
  INST__unnamed__5.METH_clean();
  INST__unnamed__7.METH_clean();
  INST_c1.METH_write(0u);
  INST_c2.METH_write(0u);
  INST_r1.METH_write(0u);
  INST_collectWindow.METH_write((tUInt8)0u);
  INST_outQ.METH_clear();
  INST_instream.METH_clear();
}

tUInt8 MOD_mkLine3::METH_RDY_clean()
{
  tUInt8 DEF_CAN_FIRE_clean;
  tUInt8 PORT_RDY_clean;
  DEF_CAN_FIRE_clean = (tUInt8)1u;
  PORT_RDY_clean = DEF_CAN_FIRE_clean;
  return PORT_RDY_clean;
}

void MOD_mkLine3::METH_loadShift(tUInt32 ARG_loadShift_inx)
{
}

tUInt8 MOD_mkLine3::METH_RDY_loadShift()
{
  tUInt8 DEF_CAN_FIRE_loadShift;
  tUInt8 PORT_RDY_loadShift;
  DEF_CAN_FIRE_loadShift = (tUInt8)1u;
  PORT_RDY_loadShift = DEF_CAN_FIRE_loadShift;
  return PORT_RDY_loadShift;
}


/* Reset routines */

void MOD_mkLine3::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_r1.reset_RST(ARG_rst_in);
  INST_outQ.reset_RST(ARG_rst_in);
  INST_instream.reset_RST(ARG_rst_in);
  INST_img.reset_RST(ARG_rst_in);
  INST_collectWindow.reset_RST(ARG_rst_in);
  INST_c2.reset_RST(ARG_rst_in);
  INST_c1.reset_RST(ARG_rst_in);
  INST_alpha.reset_RST(ARG_rst_in);
  INST__unnamed__7.reset_RST_N(ARG_rst_in);
  INST__unnamed__6.reset_RST_N(ARG_rst_in);
  INST__unnamed__5.reset_RST_N(ARG_rst_in);
  INST__unnamed__4.reset_RST_N(ARG_rst_in);
  INST__unnamed__3.reset_RST_N(ARG_rst_in);
  INST__unnamed__2.reset_RST_N(ARG_rst_in);
  INST__unnamed__1.reset_RST_N(ARG_rst_in);
  INST__unnamed_.reset_RST_N(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkLine3::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkLine3::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST__unnamed_.dump_state(indent + 2u);
  INST__unnamed__1.dump_state(indent + 2u);
  INST__unnamed__2.dump_state(indent + 2u);
  INST__unnamed__3.dump_state(indent + 2u);
  INST__unnamed__4.dump_state(indent + 2u);
  INST__unnamed__5.dump_state(indent + 2u);
  INST__unnamed__6.dump_state(indent + 2u);
  INST__unnamed__7.dump_state(indent + 2u);
  INST_alpha.dump_state(indent + 2u);
  INST_c1.dump_state(indent + 2u);
  INST_c2.dump_state(indent + 2u);
  INST_collectWindow.dump_state(indent + 2u);
  INST_img.dump_state(indent + 2u);
  INST_instream.dump_state(indent + 2u);
  INST_outQ.dump_state(indent + 2u);
  INST_r1.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkLine3::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 30u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "DONTCARE_CONCAT_unnamed__2_enQdeQ_4_5_CONCAT_u_ETC___d90", 1024u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85", 928u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_c1_1_EQ_img_2_MINUS_1_3_4_THEN_0_ELSE_c1_1__ETC___d26", 9u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "_unnamed__1_enQdeQ___d86", 128u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "_unnamed__2_enQdeQ___d84", 128u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "_unnamed__enQdeQ___d88", 128u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "b__h1288", 9u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "b__h1307", 9u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "c1_1_EQ_img_2_MINUS_1_3___d24", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "instream_first____d34", 16u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "outQ_first____d91", 1024u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "r1_7_EQ_0___d33", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "r1_7_EQ_1___d35", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "r1_7_EQ_2___d36", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "r1_7_EQ_3___d37", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "r1_7_EQ_4___d38", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "r1_7_EQ_5___d39", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "r1_7_EQ_6___d40", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "r1_7_EQ_7___d41", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h5702", 9u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "get", 512u);
  num = INST_alpha.dump_VCD_defs(num);
  num = INST_c1.dump_VCD_defs(num);
  num = INST_c2.dump_VCD_defs(num);
  num = INST_collectWindow.dump_VCD_defs(num);
  num = INST_img.dump_VCD_defs(num);
  num = INST_instream.dump_VCD_defs(num);
  num = INST_outQ.dump_VCD_defs(num);
  num = INST_r1.dump_VCD_defs(num);
  if (levels != 1u)
  {
    unsigned int l = levels == 0u ? 0u : levels - 1u;
    num = INST__unnamed_.dump_VCD_defs(l);
    num = INST__unnamed__1.dump_VCD_defs(l);
    num = INST__unnamed__2.dump_VCD_defs(l);
    num = INST__unnamed__3.dump_VCD_defs(l);
    num = INST__unnamed__4.dump_VCD_defs(l);
    num = INST__unnamed__5.dump_VCD_defs(l);
    num = INST__unnamed__6.dump_VCD_defs(l);
    num = INST__unnamed__7.dump_VCD_defs(l);
  }
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkLine3::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkLine3 &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
  if (levels != 1u)
    vcd_submodules(dt, levels - 1u, backing);
}

void MOD_mkLine3::vcd_defs(tVCDDumpType dt, MOD_mkLine3 &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1024u);
    vcd_write_x(sim_hdl, num++, 928u);
    vcd_write_x(sim_hdl, num++, 9u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 128u);
    vcd_write_x(sim_hdl, num++, 128u);
    vcd_write_x(sim_hdl, num++, 128u);
    vcd_write_x(sim_hdl, num++, 9u);
    vcd_write_x(sim_hdl, num++, 9u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 16u);
    vcd_write_x(sim_hdl, num++, 1024u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 9u);
    vcd_write_x(sim_hdl, num++, 512u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4_5_CONCAT_u_ETC___d90) != DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4_5_CONCAT_u_ETC___d90)
      {
	vcd_write_val(sim_hdl, num, DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4_5_CONCAT_u_ETC___d90, 1024u);
	backing.DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4_5_CONCAT_u_ETC___d90 = DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4_5_CONCAT_u_ETC___d90;
      }
      ++num;
      if ((backing.DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85) != DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85)
      {
	vcd_write_val(sim_hdl, num, DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85, 928u);
	backing.DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85 = DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85;
      }
      ++num;
      if ((backing.DEF_IF_c1_1_EQ_img_2_MINUS_1_3_4_THEN_0_ELSE_c1_1__ETC___d26) != DEF_IF_c1_1_EQ_img_2_MINUS_1_3_4_THEN_0_ELSE_c1_1__ETC___d26)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_c1_1_EQ_img_2_MINUS_1_3_4_THEN_0_ELSE_c1_1__ETC___d26, 9u);
	backing.DEF_IF_c1_1_EQ_img_2_MINUS_1_3_4_THEN_0_ELSE_c1_1__ETC___d26 = DEF_IF_c1_1_EQ_img_2_MINUS_1_3_4_THEN_0_ELSE_c1_1__ETC___d26;
      }
      ++num;
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF__unnamed__1_enQdeQ___d86) != DEF__unnamed__1_enQdeQ___d86)
      {
	vcd_write_val(sim_hdl, num, DEF__unnamed__1_enQdeQ___d86, 128u);
	backing.DEF__unnamed__1_enQdeQ___d86 = DEF__unnamed__1_enQdeQ___d86;
      }
      ++num;
      if ((backing.DEF__unnamed__2_enQdeQ___d84) != DEF__unnamed__2_enQdeQ___d84)
      {
	vcd_write_val(sim_hdl, num, DEF__unnamed__2_enQdeQ___d84, 128u);
	backing.DEF__unnamed__2_enQdeQ___d84 = DEF__unnamed__2_enQdeQ___d84;
      }
      ++num;
      if ((backing.DEF__unnamed__enQdeQ___d88) != DEF__unnamed__enQdeQ___d88)
      {
	vcd_write_val(sim_hdl, num, DEF__unnamed__enQdeQ___d88, 128u);
	backing.DEF__unnamed__enQdeQ___d88 = DEF__unnamed__enQdeQ___d88;
      }
      ++num;
      if ((backing.DEF_b__h1288) != DEF_b__h1288)
      {
	vcd_write_val(sim_hdl, num, DEF_b__h1288, 9u);
	backing.DEF_b__h1288 = DEF_b__h1288;
      }
      ++num;
      if ((backing.DEF_b__h1307) != DEF_b__h1307)
      {
	vcd_write_val(sim_hdl, num, DEF_b__h1307, 9u);
	backing.DEF_b__h1307 = DEF_b__h1307;
      }
      ++num;
      if ((backing.DEF_c1_1_EQ_img_2_MINUS_1_3___d24) != DEF_c1_1_EQ_img_2_MINUS_1_3___d24)
      {
	vcd_write_val(sim_hdl, num, DEF_c1_1_EQ_img_2_MINUS_1_3___d24, 1u);
	backing.DEF_c1_1_EQ_img_2_MINUS_1_3___d24 = DEF_c1_1_EQ_img_2_MINUS_1_3___d24;
      }
      ++num;
      if ((backing.DEF_instream_first____d34) != DEF_instream_first____d34)
      {
	vcd_write_val(sim_hdl, num, DEF_instream_first____d34, 16u);
	backing.DEF_instream_first____d34 = DEF_instream_first____d34;
      }
      ++num;
      if ((backing.DEF_outQ_first____d91) != DEF_outQ_first____d91)
      {
	vcd_write_val(sim_hdl, num, DEF_outQ_first____d91, 1024u);
	backing.DEF_outQ_first____d91 = DEF_outQ_first____d91;
      }
      ++num;
      if ((backing.DEF_r1_7_EQ_0___d33) != DEF_r1_7_EQ_0___d33)
      {
	vcd_write_val(sim_hdl, num, DEF_r1_7_EQ_0___d33, 1u);
	backing.DEF_r1_7_EQ_0___d33 = DEF_r1_7_EQ_0___d33;
      }
      ++num;
      if ((backing.DEF_r1_7_EQ_1___d35) != DEF_r1_7_EQ_1___d35)
      {
	vcd_write_val(sim_hdl, num, DEF_r1_7_EQ_1___d35, 1u);
	backing.DEF_r1_7_EQ_1___d35 = DEF_r1_7_EQ_1___d35;
      }
      ++num;
      if ((backing.DEF_r1_7_EQ_2___d36) != DEF_r1_7_EQ_2___d36)
      {
	vcd_write_val(sim_hdl, num, DEF_r1_7_EQ_2___d36, 1u);
	backing.DEF_r1_7_EQ_2___d36 = DEF_r1_7_EQ_2___d36;
      }
      ++num;
      if ((backing.DEF_r1_7_EQ_3___d37) != DEF_r1_7_EQ_3___d37)
      {
	vcd_write_val(sim_hdl, num, DEF_r1_7_EQ_3___d37, 1u);
	backing.DEF_r1_7_EQ_3___d37 = DEF_r1_7_EQ_3___d37;
      }
      ++num;
      if ((backing.DEF_r1_7_EQ_4___d38) != DEF_r1_7_EQ_4___d38)
      {
	vcd_write_val(sim_hdl, num, DEF_r1_7_EQ_4___d38, 1u);
	backing.DEF_r1_7_EQ_4___d38 = DEF_r1_7_EQ_4___d38;
      }
      ++num;
      if ((backing.DEF_r1_7_EQ_5___d39) != DEF_r1_7_EQ_5___d39)
      {
	vcd_write_val(sim_hdl, num, DEF_r1_7_EQ_5___d39, 1u);
	backing.DEF_r1_7_EQ_5___d39 = DEF_r1_7_EQ_5___d39;
      }
      ++num;
      if ((backing.DEF_r1_7_EQ_6___d40) != DEF_r1_7_EQ_6___d40)
      {
	vcd_write_val(sim_hdl, num, DEF_r1_7_EQ_6___d40, 1u);
	backing.DEF_r1_7_EQ_6___d40 = DEF_r1_7_EQ_6___d40;
      }
      ++num;
      if ((backing.DEF_r1_7_EQ_7___d41) != DEF_r1_7_EQ_7___d41)
      {
	vcd_write_val(sim_hdl, num, DEF_r1_7_EQ_7___d41, 1u);
	backing.DEF_r1_7_EQ_7___d41 = DEF_r1_7_EQ_7___d41;
      }
      ++num;
      if ((backing.DEF_x__h5702) != DEF_x__h5702)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h5702, 9u);
	backing.DEF_x__h5702 = DEF_x__h5702;
      }
      ++num;
      if ((backing.PORT_get) != PORT_get)
      {
	vcd_write_val(sim_hdl, num, PORT_get, 512u);
	backing.PORT_get = PORT_get;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4_5_CONCAT_u_ETC___d90, 1024u);
      backing.DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4_5_CONCAT_u_ETC___d90 = DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4_5_CONCAT_u_ETC___d90;
      vcd_write_val(sim_hdl, num++, DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85, 928u);
      backing.DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85 = DEF_DONTCARE_CONCAT_unnamed__2_enQdeQ_4___d85;
      vcd_write_val(sim_hdl, num++, DEF_IF_c1_1_EQ_img_2_MINUS_1_3_4_THEN_0_ELSE_c1_1__ETC___d26, 9u);
      backing.DEF_IF_c1_1_EQ_img_2_MINUS_1_3_4_THEN_0_ELSE_c1_1__ETC___d26 = DEF_IF_c1_1_EQ_img_2_MINUS_1_3_4_THEN_0_ELSE_c1_1__ETC___d26;
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF__unnamed__1_enQdeQ___d86, 128u);
      backing.DEF__unnamed__1_enQdeQ___d86 = DEF__unnamed__1_enQdeQ___d86;
      vcd_write_val(sim_hdl, num++, DEF__unnamed__2_enQdeQ___d84, 128u);
      backing.DEF__unnamed__2_enQdeQ___d84 = DEF__unnamed__2_enQdeQ___d84;
      vcd_write_val(sim_hdl, num++, DEF__unnamed__enQdeQ___d88, 128u);
      backing.DEF__unnamed__enQdeQ___d88 = DEF__unnamed__enQdeQ___d88;
      vcd_write_val(sim_hdl, num++, DEF_b__h1288, 9u);
      backing.DEF_b__h1288 = DEF_b__h1288;
      vcd_write_val(sim_hdl, num++, DEF_b__h1307, 9u);
      backing.DEF_b__h1307 = DEF_b__h1307;
      vcd_write_val(sim_hdl, num++, DEF_c1_1_EQ_img_2_MINUS_1_3___d24, 1u);
      backing.DEF_c1_1_EQ_img_2_MINUS_1_3___d24 = DEF_c1_1_EQ_img_2_MINUS_1_3___d24;
      vcd_write_val(sim_hdl, num++, DEF_instream_first____d34, 16u);
      backing.DEF_instream_first____d34 = DEF_instream_first____d34;
      vcd_write_val(sim_hdl, num++, DEF_outQ_first____d91, 1024u);
      backing.DEF_outQ_first____d91 = DEF_outQ_first____d91;
      vcd_write_val(sim_hdl, num++, DEF_r1_7_EQ_0___d33, 1u);
      backing.DEF_r1_7_EQ_0___d33 = DEF_r1_7_EQ_0___d33;
      vcd_write_val(sim_hdl, num++, DEF_r1_7_EQ_1___d35, 1u);
      backing.DEF_r1_7_EQ_1___d35 = DEF_r1_7_EQ_1___d35;
      vcd_write_val(sim_hdl, num++, DEF_r1_7_EQ_2___d36, 1u);
      backing.DEF_r1_7_EQ_2___d36 = DEF_r1_7_EQ_2___d36;
      vcd_write_val(sim_hdl, num++, DEF_r1_7_EQ_3___d37, 1u);
      backing.DEF_r1_7_EQ_3___d37 = DEF_r1_7_EQ_3___d37;
      vcd_write_val(sim_hdl, num++, DEF_r1_7_EQ_4___d38, 1u);
      backing.DEF_r1_7_EQ_4___d38 = DEF_r1_7_EQ_4___d38;
      vcd_write_val(sim_hdl, num++, DEF_r1_7_EQ_5___d39, 1u);
      backing.DEF_r1_7_EQ_5___d39 = DEF_r1_7_EQ_5___d39;
      vcd_write_val(sim_hdl, num++, DEF_r1_7_EQ_6___d40, 1u);
      backing.DEF_r1_7_EQ_6___d40 = DEF_r1_7_EQ_6___d40;
      vcd_write_val(sim_hdl, num++, DEF_r1_7_EQ_7___d41, 1u);
      backing.DEF_r1_7_EQ_7___d41 = DEF_r1_7_EQ_7___d41;
      vcd_write_val(sim_hdl, num++, DEF_x__h5702, 9u);
      backing.DEF_x__h5702 = DEF_x__h5702;
      vcd_write_val(sim_hdl, num++, PORT_get, 512u);
      backing.PORT_get = PORT_get;
    }
}

void MOD_mkLine3::vcd_prims(tVCDDumpType dt, MOD_mkLine3 &backing)
{
  INST_alpha.dump_VCD(dt, backing.INST_alpha);
  INST_c1.dump_VCD(dt, backing.INST_c1);
  INST_c2.dump_VCD(dt, backing.INST_c2);
  INST_collectWindow.dump_VCD(dt, backing.INST_collectWindow);
  INST_img.dump_VCD(dt, backing.INST_img);
  INST_instream.dump_VCD(dt, backing.INST_instream);
  INST_outQ.dump_VCD(dt, backing.INST_outQ);
  INST_r1.dump_VCD(dt, backing.INST_r1);
}

void MOD_mkLine3::vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkLine3 &backing)
{
  INST__unnamed_.dump_VCD(dt, levels, backing.INST__unnamed_);
  INST__unnamed__1.dump_VCD(dt, levels, backing.INST__unnamed__1);
  INST__unnamed__2.dump_VCD(dt, levels, backing.INST__unnamed__2);
  INST__unnamed__3.dump_VCD(dt, levels, backing.INST__unnamed__3);
  INST__unnamed__4.dump_VCD(dt, levels, backing.INST__unnamed__4);
  INST__unnamed__5.dump_VCD(dt, levels, backing.INST__unnamed__5);
  INST__unnamed__6.dump_VCD(dt, levels, backing.INST__unnamed__6);
  INST__unnamed__7.dump_VCD(dt, levels, backing.INST__unnamed__7);
}
